### ISSUE TITLE
Barrel Item Blacklist

### ISSUE THREAD

**Issue by J3fftw1** [lukecarr/TABBA#2]
**Is your feature request related to a problem? If so, please describe.**

**Describe the feature you'd like to be implemented:**
Being able to disable putting in some items in the barrel.
For servers that use multiple plugins with inventory related items like slimefun bagpacks.

**Comment by lukecarr** [comment]
So sort of like a barrel blacklist of what can't be put in a barrel?

**Comment by J3fftw1** [comment]
yes sir

**Comment by lukecarr** [comment]
This has been fixed in 0.1.2!
